# Generated by Django 5.2.9 on 2025-12-24 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "low_balance_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("FROZEN", "FROZEN")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="tenants.team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TOPUP", "TOPUP"),
                            ("SMS", "SMS"),
                            ("CALL", "CALL"),
                            ("NUMBER_PURCHASE", "NUMBER_PURCHASE"),
                            ("NUMBER_FEE", "NUMBER_FEE"),
                            ("ADJUSTMENT", "ADJUSTMENT"),
                            ("PLATFORM_FEE", "PLATFORM_FEE"),
                        ],
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "reference_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to="tenants.team",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="billing.wallet",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["wallet", "created_at"],
                        name="billing_wal_wallet__2827cc_idx",
                    ),
                    models.Index(
                        fields=["team", "type", "created_at"],
                        name="billing_wal_team_id_ca145a_idx",
                    ),
                ],
            },
        ),
    ]
